### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [derekleonardo/Presentaci-n-de-equipo#1]
Muy bien, jóvenes. Su página tiene buen diseño y comportamiento. 

Les adjunto unas cuantas correcciones para que realicen:
- Procuren arreglar los márgenes de las tarjetas que están en la sección "¿Por qué elegirnos?.
- Agreguen un párrafo inventado sobre la historia de su empresa.
- Confirmen que todas sus imágenes de los integrantes tengan marco circular u ovalado, sin combinar.

Espero su respuesta, etiquétenme en este Issue para enterarme que aplicaron los cambios. Saludos.

**Comment by Waterfermelon** [comment]
@CarlosRubioTNM  Resuelto ;)

**Comment by CarlosRubioTNM** [comment]
Revisado. Buen trabajo, jóvenes. 👍
